# Generated by Django 3.1.4 on 2020-12-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostRiskRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_name', models.CharField(max_length=80)),
                ('risk_lvl', models.CharField(max_length=20)),
                ('nr_incidents', models.IntegerField()),
            ],
        ),
    ]
