# Generated by Django 3.1.4 on 2020-12-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201220_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostriskrating',
            name='os_name',
            field=models.TextField(),
        ),
    ]
