# Generated by Django 3.1.4 on 2020-12-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201220_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityRiskOrigin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_name', models.TextField()),
                ('nr_incidents', models.IntegerField()),
            ],
        ),
    ]
