# Generated by Django 3.1.4 on 2020-12-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_securityriskorigin'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimalSecurity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lvl_name', models.TextField()),
                ('lvl_nr', models.IntegerField()),
            ],
        ),
    ]
